# Generated by Django 5.0.3 on 2024-03-12 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=120, unique=True, verbose_name='Apellido')),
                ('edad', models.IntegerField(verbose_name='Edad')),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'El Personal',
            },
        ),
        migrations.CreateModel(
            name='Empleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=90, verbose_name='Empleo')),
                ('tiempo_trabajando', models.DateTimeField(auto_now_add=True, verbose_name='Tiempo En Trabajo')),
                ('aspiracion', models.TextField(max_length=120, null=True, verbose_name='Aspiracion ')),
                ('experiencia', models.CharField(choices=[('P', 'Programador'), ('A', 'Administrador'), ('C', 'Chef'), ('N', 'Ninguno')], max_length=1, verbose_name='Experiencias')),
                ('persona_empleo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.personal')),
            ],
            options={
                'verbose_name': 'Empleo',
                'verbose_name_plural': 'Empleos',
            },
        ),
    ]
