# Generated by Django 5.0.3 on 2024-03-12 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleo',
            name='tiempo_trabajando',
        ),
        migrations.AlterField(
            model_name='empleo',
            name='nombre',
            field=models.CharField(max_length=90, verbose_name='Nombre Empleo'),
        ),
    ]
